### ISSUE TITLE
[QUESTION] Run checkpoint on Huggingface Transformers

### ISSUE THREAD

**Issue by Sunt-ing** [pan-x-c/EE-LLM#10]
**Your question**
Hi, thanks for providing the model checkpoint, it's really useful for me and others. It's the only open decoder-only checkpoint optimized for early exit as far as I know. 

Somehow I cannot use Megatron-LM but only Huggingface Transformers. So, how can I run early-exit inference (not necessarily using pipeline or recomputation optimizations, maybe just using fixed depths for a whole prompt) on this model checkpoint in Huggingface Transformer with a single GPU? 

Thanks for your help!

**Comment by pan-x-c** [comment]
Thanks for your attention to our EE project. However, Huggingface is currently unable to run the EE models, because the model architecture and inference method of EE models are different from standard GPT models supported by Huggingface.
Adding the EE architecture and inference method to Huggingface is a complex project and will take a lot of time. If you only have a single GPU, you can try converting our provided checkpoints into `TP=1 PP=1` and using EE-LLM inference.

**Comment by Sunt-ing** [comment]
Thanks for your advise, I will try that. BTW, do you know other open ee
checkpoints?

**Comment by yanxi-chen** [comment]
Hi! Thanks for your questions.  

There is indeed [an open multi-exit checkpoint on HuggingFace](https://huggingface.co/ibm/gpt2-medium-multiexit), although the model scale is much smaller than ours, and that work introduced multiple exits for other purposes rather than accelerating inference.

And [another early-exit work](https://github.com/raymin0223/fast_robust_early_exit) that shares fine-tuned checkpoints.

**Comment by Sunt-ing** [comment]
Thank you for the information.
